# Generated by Django 3.2.4 on 2021-06-13 19:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='image',
            old_name='image_filename',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='resizedimage',
            old_name='resized_image_filename',
            new_name='name',
        ),
        migrations.AddField(
            model_name='image',
            name='image',
            field=models.ImageField(default='1.png', max_length=512, upload_to='uploads/'),
        ),
        migrations.AddField(
            model_name='resizedimage',
            name='original',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='gallery.image'),
        ),
        migrations.AlterField(
            model_name='resizedimage',
            name='image',
            field=models.ImageField(default='1.png', max_length=512, upload_to='resized_uploads/'),
        ),
    ]
