# Generated by Django 3.2.4 on 2021-06-13 20:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0004_alter_image_url'),
    ]

    operations = [
        migrations.RenameField(
            model_name='resizedimage',
            old_name='image',
            new_name='image_resised',
        ),
        migrations.RenameField(
            model_name='resizedimage',
            old_name='name',
            new_name='name_resized',
        ),
        migrations.AlterField(
            model_name='resizedimage',
            name='original',
            field=models.ForeignKey(default='placeholder_name_resized.png', on_delete=django.db.models.deletion.CASCADE, to='gallery.image'),
        ),
    ]
