# Generated by Django 3.2.4 on 2021-06-13 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0005_auto_20210613_2339'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resizedimage',
            name='image_resised',
        ),
        migrations.AddField(
            model_name='resizedimage',
            name='image_resized',
            field=models.ImageField(default='resized_placeholder_name.png', max_length=512, upload_to='resized_uploads'),
        ),
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.ImageField(default='placeholder_name.png', max_length=512, upload_to='uploads'),
        ),
    ]
