# Generated by Django 3.2.4 on 2021-06-13 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0006_auto_20210614_0010'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='url',
            field=models.CharField(default=' ', max_length=1024),
        ),
    ]
